### ISSUE TITLE
No content to display or awaiting content load

### ISSUE THREAD

**Issue by c11umw** [petersem/posterr#261]
Updated this morning and this is all it displays on the posterr URL.
The Settings page works fine, but it's not displaying the actual posters as before.

I see there was an update on docker hub today (30mins ago), but I don't see older tags available to load in place of latest

Running in docker:
```sh
docker run -d \
--name posterr \
--network=myproxy \
-p 3000:3000 \
-v /opt/docker/posterr/config:/usr/src/app/config \
-v /opt/docker/posterr/custom:/usr/src/app/public/custom \
-e TZ=Europe/London \
--restart=always \
petersem/posterr
```

**Comment by petersem** [comment]
I did have an error in a release id just pushed in the last few hours. Should be all fixed now.

**Comment by c11umw** [comment]
> please reopen this if not working after the lastest pull v1.22.1

Got the latest, but unfortunately it still isn't working.
I purged the current image in case of corruption and got a fresh pull. No change
Then I re-applied the Plex token in case it had changed. No change
`Plex Server: 1.41.7.9823` 

Debug ping and Debug on-demand:
```
-------------------------------------------------------
 POSTERR - Your media display
 Developed by Matt Petersen - Brisbane Australia
 
 Version: 1.22.1
-------------------------------------------------------
✅ MP3 cache cleared
✅ Web server started on internal port 3000
✅ Image cache cleared
✅ Settings loaded
  
--- Enabled Status ---
   Plex: true
   Now Showing: true
   Awtrix: false
   On-demand: true
   Sonarr: false
   Radarr: false
   Custom Pictures: false
   Readarr: false
   Sleep timer: false
   Trivia: false
   Links: false
   Daily restart commencing at: 11:49:37 AM
  
 
** PING TESTS **
-------------------------------------------------------
5/28/2025, 11:50:31 AM Ping test - Plex: [IP redacted] false
5/28/2025, 11:50:31 AM Ping test - Radarr: http://[IP redacted] false
5/28/2025, 11:50:31 AM Ping test - TVDB: artworks.thetvdb.com false
5/28/2025, 11:50:31 AM Ping test - Plex Themes: tvthemes.plexapp.com false
5/28/2025, 11:50:31 AM Ping test - TMDB: https://image.tmdb.org false
5/28/2025, 11:50:31 AM Ping test - Open Trivia DB: https://opentdb.com false
 
** PLEX 'ON-DEMAND' CHECK **
-------------------------------------------------------
5/28/2025, 11:50:41 AM *On-demand - title retrieval: Error: Plex Server didnt respond with status code 200, response code: 404
```

Manual ping is confirmed from OS > LAN Plex server.
Unable to ping from inside the posterr container as ping isn't installed.
